name: qr-game
services:
#  - name: api
#    project: api/api.csproj
#    bindings:
#      - protocol: https
#        port: 5001
        
#  - name: frontend
#    dockerFile: frontend/Dockerfile
#    bindings:
#      - protocol: http
#        port: 4400
        
  - name: postgres
    image: postgres:14
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: password
      - name: POSTGRES_DB
        value: postgres
    bindings:
      - port: 5432
        connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};
    volumes:
      - name: postgres-storage
        target: /var/lib/postgresql/data
#        
#  - name: directus
#    image: directus/directus:latest
#    bindings:
#      - port: 8055
#    env:
#      - name: KEY
#        value: '255d861b-5ea1-5996-9aa3-922530ec40b1'
#      - name: secret
#        value: '6116487b-cda1-52c2-b5b5-c8022c45e263'
#      - name: 
#        value: 'pg'
##    - name: KEY
##      value '255d861b-5ea1-5996-9aa3-922530ec40b1'
##      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
##      
##      DB_CLIENT: 'pg'
##      DB_HOST: 'database'
##      DB_PORT: '5432'
##      DB_DATABASE: 'buk-universal-games'
##      DB_USER: 'admin'
##      DB_PASSWORD: 'password'
##      
##      CACHE_ENABLED: 'true'
##      CACHE_STORE: 'redis'
##      CACHE_REDIS: 'redis://redis:6379'
##      
##      ADMIN_EMAIL: 'admin@admin.com'
##      ADMIN_PASSWORD: 'password'