name: Trigger auto deployment for qr-code-run-prod-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'api/**'
    - '.github/workflows/qr-code-run-prod-api-AutoDeployTrigger-1b0e47d7-2b74-4e49-89a8-3257d76ad8c1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            bccplatform.azurecr.io/qr-code-run-prod-api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: bccplatform.azurecr.io
          username: ${{ secrets.QRCODERUNPRODAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.QRCODERUNPRODAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          file: api/Dockerfile
          context: api


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.QRCODERUNPRODAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n qr-code-run-prod-api -g qr-code-run-prod --server bccplatform.azurecr.io --username  ${{ secrets.QRCODERUNPRODAPI_REGISTRY_USERNAME }} --password ${{ secrets.QRCODERUNPRODAPI_REGISTRY_PASSWORD }}
            az containerapp update -n qr-code-run-prod-api -g qr-code-run-prod --image bccplatform.azurecr.io/qr-code-run-prod-api:${{ github.sha }}
